### ISSUE TITLE
IndexError: list index out of rangeと表示されます。

### ISSUE THREAD

**Issue by wimpykid719** [mocobeta/janome#48]
卒業制作でクローラーを制作しながらPythonを勉強しているのですが、このようなエラーが出て困っています。何が原因なのかさっぱりわからないのでお力を貸して頂けないでしょうか？
よろしくお願いします。

文字列として渡す値に問題があるような気がするのですが、リスト配列からはみ出ているというのがよくわかりません。

**エラー内容**
```
Traceback (most recent call last):
  File "/vagrant/pysearch-master/manage.py", line 15, in <module>
    crawl_web('https://news.google.com/news/headlines?hl=ja&ned=jp', 3)
  File "/vagrant/pysearch-master/web_crawler/crawler.py", line 137, in crawl_web
    add_page_to_index(page_url, html)
  File "/vagrant/pysearch-master/web_crawler/crawler.py", line 121, in add_page_to_index
    for word in _split_to_word(line): #janomeで日本語形態解析して単語をwordに代入
  File "/vagrant/pysearch-master/web_crawler/crawler.py", line 45, in _split_to_word
    return [token.surface for token in t.tokenize(text)]
  File "/home/vagrant/.virtualenvs/dev/local/lib/python3.4/site-packages/janome/tokenizer.py", line 193, in tokenize
    return list(self.__tokenize_stream(text, wakati))
  File "/home/vagrant/.virtualenvs/dev/local/lib/python3.4/site-packages/janome/tokenizer.py", line 200, in __tokenize_stream
    tokens, pos = self.__tokenize_partial(text[processed:], wakati)
  File "/home/vagrant/.virtualenvs/dev/local/lib/python3.4/site-packages/janome/tokenizer.py", line 254, in __tokenize_partial
    lattice.end()
  File "/home/vagrant/.virtualenvs/dev/local/lib/python3.4/site-packages/janome/lattice.py", line 154, in end
    self.add(eos)
  File "/home/vagrant/.virtualenvs/dev/local/lib/python3.4/site-packages/janome/lattice.py", line 140, in add
    node.index = len(self.snodes[self.p])
IndexError: list index out of range
```

**htmlからbody以下にあるタグの中にあるテキストを解析に渡す**
```
def add_page_to_index(url, html):
    body_soup = BeautifulSoup(html, "html.parser").find('body')
    #htmlないの属性タグとその中身をchild_tagに入れていってる<body>以下にある全てのタグ<a>やら<th>やらを持ってくる。
    #先ずはbodyより下のhtml全部持ってきて次にその下のdivを持ってきてul持ってきてどんどん掘り下げる感じ
    #if body_soup.findChildren() is not None:
    for child_tag in body_soup.findChildren():
        #beautifulsoupの機能でタグの名前だけ取り出してる。スクリプトだけは避ける。それ以降の処理がスキップされてループに戻る
        if child_tag.name == 'script': #child_tag.nameタグの名前を取り出す
            continue
        #.textはそのタグの中身を表示する。<a>link</a>だったらlinkだけとりだす。
        child_text = child_tag.text
        for line in child_text.split('\n'): #文字列から改行を取り除いて分ける。
            line = line.rstrip().lstrip() #上のコードだけだと両端の空白が消せないからここで削除している。実際には削除はできないので取り除いたのを返している
            for word in _split_to_word(line): #janomeで日本語形態解析して単語をwordに代入
                add_to_index(word, url)
```
**add_page_to_indexで文字列で受け取ったテキストを解析して単語にして返す**
```
def _split_to_word(text):
    """Japanese morphological analysis with janome.
    Splitting text and creating words list.
    """
    t = Tokenizer()
    #token.surfaceで日本語の文字だけ取り出せる。例えば車は高いだったら"車" "は" "高い" だけ取り出せる。
    return [token.surface for token in t.tokenize(text)]
```

**Comment by mocobeta** [comment]
エラーを再現させたいのですが、具体的に、解析でエラーになる文字列を教えていただけますか？

**Comment by wimpykid719** [comment]
申し訳ありません。googleのトップページから7個のURLを探索する設定でクローリングしている途中で発生したのでどの文字列なのか特定するのが厳しいです。現在どこのurlページでそうなるのか捜査中です。

**Comment by wimpykid719** [comment]
URLは特定しました。googleの設定ページのようです。
https://www.google.co.jp//preferences?hl=ja

**Comment by wimpykid719** [comment]
文字列特定しました。
これだけの文字列を一気に渡していたみたいです。

**文字列**
`表示設定Google アカウント設定 | 設定のヘルプ | Google について 設定を保存して、検索に戻る共通設定 (すべての Google サービスに適用されます)クッキー機能が無効になっている可能性があります。「表示設定」を保存するには、ご利用のブラウザのクッキー設定を有効にする必要があります。 クッキーの設定方法var selected_hl_checked_by_user=false;var currently_selected_hl="ja";var hl_lp_map={"ach":"en","ban":"en","bem":"en","ckb":"en","es-419":"en","kg":"en","nn":"no","nyn":"en","pcm":"en","pt-BR":"pt","pt-PT":"pt","tlh":"en","xx-bork":"en","xx-elmer":"en","xx-hacker":"en","xx-pirate":"en"};function fnDisable(hl){var textspan=document.getElementById("t"+hl);if(textspan)textspan.className='disabled';var tickbox=document.getElementById("p"+hl);if(tickbox)tickbox.disabled=true;return tickbox}function fnEnable(hl){var textspan=document.getElementById("t"+hl);if(textspan)textspan.className=null;var tickbox=document.getElementById("p"+hl);if(tickbox)tickbox.disabled=false;return tickbox}function fnSetInitialPreferences(){var tickbox=fnDisable(currently_selected_hl);if(tickbox)tickbox.checked=true}function fnHlToPref(hl){if(hl_lp_map[hl]){return hl_lp_map[hl]}return hl}function fnSelectionChanged(new_hl){var tickbox=fnEnable(fnHlToPref(currently_selected_hl));if(tickbox)tickbox.checked=selected_hl_checked_by_user;tickbox=fnDisable(fnHlToPref(new_hl));if(tickbox){selected_hl_checked_by_user=tickbox.checked;tickbox.checked=true;}else{selected_hl_checked_by_user=false;}currently_selected_hl=new_hl}var num_langprefs_checked=0;function tick(){var count=0;for(var i=0;i<document.langform.lr.length;++i)if(document.langform.lr[i].checked)++count;if(count>8&&count>num_langprefs_checked){alert("言語制限の数は最大 8 です。選択された言語のうち 8 のみが保存されます。");}num_langprefs_checked=count}  表示言語の設定Google のメニューやテキストの言語: Acoli Afrikaans Akan azərbaycan Bahasa Melayu Balinese Bork, bork, bork! bosanski brezhoneg català Cebuano čeština chiShona Corsican Cymraeg dansk Deutsch Èdè Yorùbá eesti Elmer Fudd English español español (Latinoamérica) esperanto euskara Eʋegbe Filipino føroyskt français Ga Gaeilge Gàidhlig galego Guarani Hacker Haitian Creole Hausa hrvatski ʻŌlelo Hawaiʻi Ichibemba Igbo Ikirundi Indonesia Interlingua isiZulu íslenska italiano Javanese Kinyarwanda Kiswahili Klingon Kongo kreol morisien Krio (Sierra Leone) Latin latviešu lea fakatonga lietuvių lingála Lozi Luba-Lulua Luganda magyar Malagasy Malti Maori Nederlands Nigerian Pidgin norsk Northern Sotho Nyanja nynorsk o‘zbek Occitan Oromoo Pirate polski português (Brasil) português (Portugal) română rumantsch Runasimi Runyankore Seychellois Creole shqip Sindhi slovenčina slovenščina Soomaali Southern Sotho srpski (Crna Gora) srpski (latinica) Sundanese suomi svenska Tajik Tatar Tiếng Việt Tswana Tumbuka Türkçe Turkmen Twi West-Frysk Wolof Xhosa Ελληνικά беларуская български кыргызча қазақ тілі македонски монгол русский српски українська ქართული հայերեն ייִדיש עברית ئۇيغۇرچە اردو العربية پښتو فارسی کوردیی ناوەندی ትግርኛ አማርኛ नेपाली मराठी हिन्दी বাংলা ਪੰਜਾਬੀ ગુજરાતી ଓଡ଼ିଆ தமிழ் తెలుగు ಕನ್ನಡ മലയാളം සිංහල ไทย ລາວ မြန်မာ ខ្មែរ ᏣᎳᎩ 한국어 中文 (简体) 中文 (繁體) 日本語    検索言語の設定 優先する言語: Afrikaans  català  čeština  dansk  Deutsch  eesti  English  español  esperanto  Filipino  français  hrvatski  Indonesia  íslenska  italiano  Kiswahili  latviešu  lietuvių  magyar  Nederlands  norsk  polski  português  română  slovenčina  slovenščina  suomi  svenska  Tiếng Việt  Türkçe  Ελληνικά  беларуская  български  русский  српски  українська  հայերեն  עברית  العربية  فارسی  हिन्दी  ไทย  한국어  中文 (简体)  中文 (繁體)  日本語 fnSetInitialPreferences()  地域の設定現在の地域 アイスランド アイルランド アゼルバイジャン アフガニスタン アメリカ合衆国 アラブ首長国連邦 アルジェリア アルゼンチン アルバニア アルメニア アンギラ アンゴラ アンティグア・バーブーダ アンドラ イギリス イスラエル イタリア イラク インド インドネシア ウガンダ ウクライナ ウズベキスタン ウルグアイ エクアドル エジプト エストニア エチオピア エルサルバドル オーストラリア オーストリア オマーン オランダ ガーナ カーボベルデ ガーンジー ガイアナ カザフスタン カタール カナダ ガボン カメルーン ガンビア カンボジア キプロス キューバ ギリシャ キリバス キルギス グアテマラ グアドループ クウェート クック諸島 グリーンランド クロアチア ケニア コートジボワール コスタリカ コロンビア コンゴ共和国(ブラザビル) コンゴ民主共和国(キンシャサ) サウジアラビア サモア サントメ・プリンシペ ザンビア サンマリノ シエラレオネ ジブチ ジブラルタル ジャージー ジャマイカ ジョージア シンガポール ジンバブエ スイス スウェーデン スペイン スリナム スリランカ スロバキア スロベニア セーシェル セネガル セルビア セントビンセント及びグレナディーン諸島 セントヘレナ ソマリア ソロモン諸島 タイ タジキスタン タンザニア チェコ チャド チュニジア チリ デンマーク トーゴ ドイツ トケラウ ドミニカ共和国 ドミニカ国 トリニダード・トバゴ トルクメニスタン トルコ トンガ ナイジェリア ナウル ナミビア ニウエ ニカラグア ニジェール ニュージーランド ネパール ノーフォーク島 ノルウェー バーレーン ハイチ パキスタン パナマ バヌアツ バハマ パプアニューギニア パラグアイ パレスチナ ハンガリー バングラデシュ ピトケアン諸島 ブータン フィジー フィリピン フィンランド プエルトリコ ブラジル フランス ブルガリア ブルキナファソ ブルネイ ブルンジ ベトナム ベナン ベネズエラ ベラルーシ ベリーズ ペルー ベルギー ポーランド ボスニア・ヘルツェゴビナ ボツワナ ボリビア ポルトガル ホンジュラス マケドニア(旧ユーゴスラビア共和国) マダガスカル マラウイ マリ マルタ マレーシア マン島 ミクロネシア連邦 ミャンマー メキシコ モーリシャス モザンビーク モルディブ モルドバ モロッコ モンゴル モンテネグロ モントセラト ヨルダン ラオス ラトビア リトアニア リビア リヒテンシュタイン ルーマニア ルクセンブルク ルワンダ レソト レバノン ロシア 中央アフリカ共和国 南アフリカ 台湾 大韓民国 日本 東ティモール 米領ヴァージン諸島 米領サモア 英領ヴァージン諸島 香港    セーフサーチ フィルタリングGoogle セーフサーチは、アダルトコンテンツを含むページを検索結果から除外します。  最も関連性の高い検索結果を表示不適切な検索結果を除外する。 セーフサーチをロック このブラウザを使用してこのパソコンから実行するすべての検索に「フィルタリング（強）」が適用されます。詳細  検索結果の表示件数 Google のデフォルト (10 件) が検索結果を最も速く表示できます。10203050100 件ずつ表示する    結果ウィンドウ    検索結果を新しいウィンドウで開く。 設定を保存して、検索に戻る©2017 Google`

**Comment by mocobeta** [comment]
ありがとうございます！確認します。

**Comment by wimpykid719** [comment]
よろしくお願いします！

**Comment by mocobeta** [comment]
@wimpykid719 ご報告ありがとうございました。修正したモジュールをPyPIにアップロードしました。バージョンは， `0.3.6` です。janome のアップデートをお願いします。
