### ISSUE TITLE
janomeトークナイズ、NEologd辞書と簡略辞書の併用時のエラーについて

### ISSUE THREAD

**Issue by SKIYOH** [mocobeta/janome#53]
Twitterを送らせていただきました、SKIYOです。

指示の通り、コードとエラーを記載します。
（なお、プライバシーに関係しそうな箇所を---にしています）

▼Code
`import pandas as pd
import codecs as cd
import numpy as np
import math
import re
import xlrd
import xlsxwriter
from collections import Counter
from itertools import chain
from janome.tokenizer import Tokenizer
import os
import csv

### データセット整形
with cd.open(r"\\Saigo\RedirectedFolders\---.csv", "r", "utf-8") as file:
    df = pd.read_csv(file)
    
## 行drop
df.dropna(how='any', inplace=True)
#how='any'：一つでもNaN(Not a Number)がある行/列(,axis=1)をdrop　なお、how='all'は全てがNaNをdrop
#inplace=True：元のdfが変更される。

## 昇順ソート
df.sort_values(by='顧客ID', inplace=True)
#axis=1：列方向にソート　ascending=False：降順でソート　by='列名'：その列内の値がソート基準になる

### ユーザ辞書の設定
t = Tokenizer(r"C:\Box Sync\Desktop\---\dict_simple_utf8sig.csv", udic_type="simpledic", udic_enc="utf-8-sig", mmap=True)#Tokenizer初期化

### Tokenize
data = []
each_data = []
ID_data = []
for i in range(len(df.index)):
    ID = df.iat[i, 0]
    value = df.iat[i, 1] #.iat[行番号, 列番号]　なお、.at['行ラベル', '列ラベル']も可能
    tokens = t.tokenize(value)
    for token in tokens:
        partOfSpeech = token.part_of_speech.split(',')[0] #.part_of_speech.split(',')[0]：品詞
        #なお、[1]~[3]は品詞細分類1~3
        #その他、.infl_type：活用型、.infl_form：活用形、.base_form：原形、.reading：読み、.phonetic：発音
        if partOfSpeech == u'名詞': #名詞を抽出する
            each_data.append(token.surface) #.surface：表層形（tokenそのもの）
    if i != 0:
        if ID != df.iat[i-1, 0]:
            each_data.insert(0, ID)
            data.append(each_data)
            each_data = []
    if len(data) == 10:
        break

### エクセル作成
#ファイル作成
output_Exl = xlsxwriter.Workbook(r"result_pd\morphology_wUserdict.xlsx")
#シート作成
output_sht = output_Exl.add_worksheet('tokens')

for row in range(len(data)):
    for i in range(len(data[row])):
        output_sht.write(row, i, data[row][i]) # (行, 列, 追加するデータ)

##data（リストのリスト）内のすべてのtokensを同じリストに格納
chain_data = list(chain.from_iterable(data)) #chain(.from_iterable)()：iterableなオブジェクトを一つのオブジェクトにまとめる
#http://coolpythontips.blogspot.com/2016/02/itertoolschain.html

c = Counter(chain_data) #Counterは、keyに要素、valueに出現回数の、辞書型のサブクラス
result_ranking = c.most_common() #(要素, 出現回数)という形のタプルを出現回数が多い順に並べたリストを返す。引数にnを入力すると、上位n位までを対象にする。
#https://note.nkmk.me/python-collections-counter/

ranking = output_Exl.add_worksheet('count')
for row in range(len(result_ranking)):
    for i in range(len(result_ranking[row])):
        ranking.write(row, i, result_ranking[row][i])
#
output_Exl.close() #エクセル保存
`

▼error
Traceback (most recent call last):
  File ".\tokenizing_SFDC_pd.py", line 32, in <module>
    t = Tokenizer(r"C:\Box Sync\Desktop\---\dict_simple_utf8sig.csv", udic_type="simpledic", udic_enc="utf-8-sig", mmap=True)#Tokenizer初期化
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\janome\tokenizer.py", line 168, in __init__
    self.user_dic = UserDictionary(udic, udic_enc, udic_type, connections)
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\janome\dic.py", line 374, in __init__
    compiledFST, entries = build_method(user_dict, enc)
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\janome\dic.py", line 404, in buildsimpledic
    surface, pos_major, reading = line.split(',')
ValueError: too many values to unpack (expected 3)

**Comment by SKIYOH** [comment]
code中の \# がタイトルとして認識されてしまいました。。

**Comment by mocobeta** [comment]
issue ありがとうございます。

FYI: コードは "```" で囲うとコードブロックになります。ちょっといじらせてもらいました

手元では，NEologd 同梱版で，ユーザー辞書(utf8)を使って解析ができました。

辞書のフォーマットが仕様どおりではない可能性がありますが， `dict_simple_utf8sig.csv` に余計な `,` が入っていないでしょうか。 

```
ゼロ高,カスタム名詞,ゼロコウ
```
はOKですが
```
ゼロ高,カスタム名詞,ゼロコウ,abc
```
のように `,` が3つ以上あるとこのエラーが出るようです。

（今の所，`,` を含む単語をユーザー辞書には追加できません。）

**Comment by SKIYOH** [comment]
早速対応くださり、ありがとうございます！！
なるほど、そういうことだったのですね！orz
ユーザー辞書は、大量の単語帳から機械的に引っ張ってきて作成したため、\, を含む可能性は大いにありそうです。
まずはユーザー辞書を目検して、\, が含まれていそうかざっと見てみます。

\, を無くした上でもエラーが出るようでしたら、再度質問させていただけたら幸甚です。

改めまして、この度はありがとうございました。
本当に助かりました。
