### ISSUE TITLE
Foollowing import "from janome.tokenizer import Tokenizer" causes imports of other libraries (e.g. boto3 or aiohttp) in python 3 to fail

### ISSUE THREAD

**Issue by quaizarv** [mocobeta/janome#61]

**Comment by quaizarv** [comment]
Simply try the following:

```import boto3
from janome.tokenizer import Tokenizer
s3_client = boto3.client('s3')
```

This will show the following error

```
(env3) quaizars-mbp(~/work/rupert)>python algo/test2.py 
Traceback (most recent call last):
  File "algo/test2.py", line 3, in <module>
    s3_client = boto3.client('s3')
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/botocore/client.py", line 65, in create_client
    cls = self._create_client_class(service_name, service_model)
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/botocore/client.py", line 89, in _create_client_class
    base_classes=bases)
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/boto3/utils.py", line 61, in _handler
    module = import_module(module)
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/boto3/utils.py", line 52, in import_module
    __import__(name)
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/boto3/s3/inject.py", line 15, in <module>
    from boto3.s3.transfer import create_transfer_manager
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/boto3/s3/transfer.py", line 127, in <module>
    from s3transfer.exceptions import RetriesExceededError as \
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/s3transfer/__init__.py", line 134, in <module>
    import concurrent.futures
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/Users/quaizar/work/env3/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

The problem is caused by the line "sys.path.insert(0, parent_dir)" in sysadic/__init__.py
```
import os, sys
base_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(base_dir)
sys.path.insert(0, parent_dir)
...
```
If you comment this line out, things work fine.

**Comment by mocobeta** [comment]
I tried to reproduce the error but it did not occurred.

```
(venv) $ python -V
Python 3.6.6

(venv) $ pip freeze
boto3==1.9.107
botocore==1.12.107
docutils==0.14
Janome==0.3.7
jmespath==0.9.4
python-dateutil==2.8.0
s3transfer==0.2.0
six==1.12.0
urllib3==1.24.1

(venv) $ python
Python 3.6.6 (default, Jul 19 2018, 16:29:00) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> from janome.tokenizer import Tokenizer
>>> s3_client = boto3.client('s3')
>>> 
```

Can you please provide more specific information for reproducing?

**Comment by emadg** [comment]
I have the same issue.
After this in my code:
from janome.tokenizer import Tokenizer

The sys.path is changed so that Janome package path is first in the sys.path list and causes other imports from my code to fail.

Especially, I have a version.py in my code and when I do import in my code like this:

My code module: (version.py)
# My project server version
_ver = 'v1.0'

and in another part of my code: (main.py)
from version import _ver

This raises an import Error.

**Comment by mocobeta** [comment]
Thanks for reporting with reproducible example! Actually the sys.path change isn't needed for latest Janome at all. I've uploaded v0.3.10 that only includes the patch #69 to PyPI.
This should fix the problem, can you check the latest version (0.3.10)?
